name: CI/CD
on:
  push:
    branches:
      - "main"
    # pull_request_target:
    #   types:
    #     - closed
    #   branches:
    #     - "Agregador-*"
jobs:
  create_pull_request:
    # if: github.event.pull_request.merged == true
    steps:
      - name: Creating pull request to Homologacao-interno
        run: gh pr create -B Agregador-GT-A -H homologacao-interno --title 'Merge branch_to_merge into base_branch' --body 'Created by Github action'
        env:
            GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}      