name: Auto merge em pull request na branch homologao-interno
on:
  pull_request:

jobs:

  merge_pull_request:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v2
      - name: Realizando merge
        run: gh pr merge --merge 
        env:
          GITHUB_TOKEN: ${{ github.token }}      

