name: Criar pull request para homologao-interno
on:
  push:
    branches:
      - "Agregador-*"
    # pull_request_target:
    #   types:
    #     - closed
    #   branches:
    #     - "Agregador-*"
jobs:

  create_pull_request:
    runs-on: ubuntu-latest
    # if: github.event.pull_request.merged == true
    steps:
      - name: Checkout repository
        uses: actions/checkout@v2
      - name: Creating pull request to Homologacao-interno
        run: gh pr create -B homologacao-interno -H '${{ github.event.pull_request.base.ref }}'  --title '${{ github.event.pull_request.title }}' --body 'Created by Github action'
        env:
            GITHUB_TOKEN: ${{ github.token }}    
